version: '2.4'

services:
  bot:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./views:/usr/sms-next/views
    ports:
      - 4317:4317
    expose:
      - 4317

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    expose: 
      - '6379'
    ports: 
      - '6379:6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fyko
      POSTGRES_PASSWORD: doctordoctor
      POSTGRES_DB: sms-next
    ports:
      - 5432:5432

volumes:
  postgres_data:
  redis_data:
